compute_environment: LOCAL_MACHINE
debug: false
distributed_type: DEEPSPEED
downcast_bf16: 'yes'
#enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
#mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
#gpu_ids: 1,3,4,5,6,7
#gpu_ids: 1,3,4,5,7
gpu_ids: 1,3
main_process_port: 32613
